# Generated by Django 5.1.4 on 2024-12-14 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0004_rename_hotel_image_hotelimage_hotel_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='booking_app.country'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='country_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='booking_app.country'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='country_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='booking_app.country'),
        ),
    ]
